version: "3.4"

services:
  web:
    container_name: web
    image: web-dev:1.0.0
    build:
      context: .
      dockerfile: .dev.web.Dockerfile
    # depends_on:
    #   - api
    ports:
      - 3000:3000
      - 49153:49153
    restart: on-failure:3
    volumes:
      - ./:/app
      - ./app/node_modules/ # Just specify a path and let the Engine create a volume
  # api:
  #   container_name: collection-service
  #   image: collection-service-dev:1.0.0
  #   build:
  #     context: .
  #     dockerfile: .dev.Dockerfile
  #   # depends_on:
  #   #   - eventstore-db
  #   # command: yarn start:dev
  #   ports:
  #     - 3000:3000
  #   networks:
  #     - collection-service-network
  # eventstore-db:
  #   container_name: eventstore-db
  #   image: eventstore/eventstore:20.10.2-buster-slim
  #   environment:
  #     - EVENTSTORE_CLUSTER_SIZE=1
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #     - EVENTSTORE_EXT_TCP_PORT=1113
  #     - EVENTSTORE_HTTP_PORT=2113
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
  #     - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  #   ports:
  #     - "1113:1113"
  #     - "2113:2113"
  #   volumes:
  #     - type: volume
  #       source: eventstore-volume-data
  #       target: /var/lib/eventstore
  #     - type: volume
  #       source: eventstore-volume-logs
  #       target: /var/log/eventstore

# volumes:
#   eventstore-volume-data:
#   eventstore-volume-logs:

# networks:
#   web-network:
