version: "3.4"

services:
  web:
    container_name: web
    image: web-dev:1.0.0
    # depends_on:
    #   - api
    build:
      context: .
      dockerfile: apps/neweb/.docker/web.Dockerfile
      target: development
    ports:
      # Exposing Next.js app port and
      # Webpack default hot reload port respectively:
      - 3000:3000
      - 49153:49153
    restart: on-failure:3
    volumes:
      - ./:/app
      - ./app/node_modules/

  api:
    container_name: api
    image: api-dev:1.0.0
    # depends_on:
    #   - eventstore-db
    build:
      context: .
      dockerfile: apps/neweb/.docker/api.Dockerfile
      target: development
    ports:
      - 4000:4000
    restart: on-failure:3
    volumes:
      - ./:/app
      - ./app/node_modules/

  # eventstore-db:
  #   container_name: eventstore-db
  #   image: eventstore/eventstore:20.10.2-buster-slim
  #   environment:
  #     - EVENTSTORE_CLUSTER_SIZE=1
  #     - EVENTSTORE_RUN_PROJECTIONS=All
  #     - EVENTSTORE_START_STANDARD_PROJECTIONS=true
  #     - EVENTSTORE_EXT_TCP_PORT=1113
  #     - EVENTSTORE_HTTP_PORT=2113
  #     - EVENTSTORE_INSECURE=true
  #     - EVENTSTORE_ENABLE_EXTERNAL_TCP=true
  #     - EVENTSTORE_ENABLE_ATOM_PUB_OVER_HTTP=true
  #   ports:
  #     - "1113:1113"
  #     - "2113:2113"
  #   volumes:
  #     - type: volume
  #       source: eventstore-volume-data
  #       target: /var/lib/eventstore
  #     - type: volume
  #       source: eventstore-volume-logs
  #       target: /var/log/eventstore

# volumes:
#   eventstore-volume-data:
#   eventstore-volume-logs:
